Dibware.Template.Presentation.Web/Models/Home/StatusViewModel.cs
using Dibware.Template.Presentation.Web.Models.Base;
using System;

namespace Dibware.Template.Presentation.Web.Models.Home
{
    public class StatusViewModel : BaseViewModel
    {
        /// <summary>
        /// Gets or sets the message.
        /// </summary>
        /// <value>
        /// The message.
        /// </value>
        public String Message { get; set; }
    }
}

Dibware.Template.Presentation.Web/Controllers/NavigationController.cs
using Dibware.Template.Presentation.Web.Controllers.Base;
using Dibware.Template.Presentation.Web.Models.Navigation;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace Dibware.Template.Presentation.Web.Controllers
{
    public class NavigationController : BaseController
    {
        #region Actions

        /// <summary>
        /// Returs a partial View for the header navigation
        /// </summary>
        /// <returns></returns>
        public PartialViewResult HeaderNavigation()
        {
            // Create model
            HeaderNavigationViewModel model = new HeaderNavigationViewModel();

            // Create Nav Items
            List<NavigationItem> navigationItems = new List<NavigationItem>();

            // Get current node
            SiteMapNode rootNode = SiteMap.RootNode;

            // Get all children of the root node and add them
            // into the navigation items collection
            foreach (SiteMapNode childNode in rootNode.ChildNodes)
            {
                // Create a navigation item from the child node
                var item = new NavigationItem()
                {
                    Description = childNode.Description,
                    Title = childNode.Title,
                    Url = Url.Content(childNode.Url)
                };

                // Add to list
                navigationItems.Add(item);
            }

            // Set nav items to model
            model.NavigationItems = navigationItems;

            return PartialView(model);
        }

        #endregion
    }
}

Dibware.Template.Presentation.Web/Views/Shared/Status.cshtml
@using Dibware.Template.Presentation.Web.Resources
@model Dibware.Template.Presentation.Web.Models.Home.StatusViewModel

<section id="statusPage">
  <p></p>
  <div class="jumbotron">
    <div class="container">
      <h1>@PageTitles.WebsiteStatus</h1>
      <h4>@Model.Message</h4>
    </div>
  </div>
</section>

Dibware.Template.Presentation.Web/Views/Shared/_Layout.cshtml
@using Dibware.Template.Presentation.Web.Models.Base
@using Dibware.Template.Presentation.Web.Resources
@model Dibware.Template.Presentation.Web.Models.Base.BaseViewModel

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="application-name" content="@Model.BrandName" />
    <meta name="msapplication-navbutton-color" content="#DDDDDD" />
    <meta name="msapplication-window" content="width=1024;height=768" />
    <meta name="msapplication-starturl" content="/" />
    <meta name="msapplication-tooltip" content="@Model.PageTitle" />
    <meta name="description" content="@Model.MetaDescription"/>
    <meta name="author" content="@Model.MetaAuthor"/>
    @RenderSection("Metadata", required: false)
    <title>@Model.PageTitle</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    @* Add Stylesheets *@
    <!-- Stylesheets -->
    @foreach (var styleBundlePath in Model.StylesheetBundlePathList)
    {
      @Styles.Render(styleBundlePath)
    }
    <!-- Stylesheets -->
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          @if (Model.HasBrandName)
          {
            @Html.ActionLink(Model.BrandName, "Index", "Home", null, new {@class = "navbar-brand"})
          }
        </div>
        <div class="collapse navbar-collapse">
          @{ Html.RenderAction("HeaderNavigation", "Navigation", new { area = "" }); }
        </div><!-- /. collapse navbar-collapse -->
      </div>
    </div>

    <div class="container main-content">
      <div>
        @RenderBody()
      </div>
    </div><!-- /.container .main-content -->

    
    @*
      Add Javascript at the end of the document 
      so the browser can begin rendering sooner 
    *@
    <!-- Javascript files -->
    @foreach (var scriptBundlePath in Model.JavaScriptBundlePathList)
    {
      @Scripts.Render(scriptBundlePath)
    }
    <!-- Javascript files -->

    <!-- Page Javascript -->
    @RenderSection("scripts", required: false)

    @if(Model.HasNotifications)
    {
      <script>
        $(document).ready(function(){
          @foreach (var notification in Model.Notifications)
          {
            Html.RenderPartial("~/Views/JavascriptPartialViews/_BootBar.cshtml", notification);
          }
        });
        var url = '@Url.Action("dismissnotification", "notifications")';
        dibware.notifications.init(url);
      </script>
    }
    <!-- page Javascript -->
  </body>
</html>